name: Build and test rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_rust_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libasound for alsa
      run: sudo apt-get install libasound2-dev
    - name: Install libudev
      run: sudo apt-get install libudev-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
